services:
  ecommerce-express-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: ecommerce-express-app  
    volumes:
      - ./src:/app/src
    container_name: ecommerce-node-docker
    expose:
      - '3001'
    ports:
      - '4000:3001'
    command: npm run dev