version: '3.7'

services:
  AmazonCloneNodeJS-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    container_name: ecommerce-node-docker
    expose:
      - '4000'
    ports:
      - '4000:3001'
    command: npm run dev