name : Build on PR

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest

    steps:
      -name: Checkout the repository
      uses: actions/checkout@v3

      -name: Install Dependencies
      uses: actions/setup-node@v3
      run: npm install

      -name: Build the package
      run: npm run build

      -name: Run lint
      run: npm run lint

      # -name: run tests
      # run: npm run test-jest
      # run: npm run test-mocha

