name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4  

      - name: Checking the foldar structure
        run: ls -l

      - name: Creating foldar
        run: mkdir certificates

      - name: Create Env File
        run: echo "${{secrets.ENV_FILE}}" > .env

      - name: List certificates directory
        run: ls -l certificates
        
      - name: Setup service account key  
        run: echo "${{secrets.SERVICE_ACCOUNT_KEY}}" > ./certificates/service_account.json  

      - name: Setup ssh key
        run: echo "${{secrets.DB_SSH_KEY}}" > ./certificates/X509-cert-4872692784746398304.pem

      - name: Install Dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Run lint
        run: npm run lint

      # Uncomment and customize below for running tests if needed
      # - name: Run tests
      #   run: npm run test