name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3  

      - name: Setup ssh key
        run: echo "${{ secrets.DB_SSH_KEY }}" > certificates/X509-cert-4872692784746398304.pem

      - name: Setup service account key  
        run: echo "${{secrets.SERVICE_ACCOUNT_KEY}}" > certificates/service_account.json

      - name: Create Env File
        run: 'echo "${{secrets.ENV_FILE}}" > .env'

      - name: Install Dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Run lint
        run: npm run lint

      # Uncomment and customize below for running tests if needed
      # - name: Run tests
      #   run: npm run test